id: 90b44830884c4fcf9dadbcf3e0bfbd8c
initial_creation_type: ocr
created_at: 28/09/2021
last_modified_at: 26/11/2021
source_metadata:
  id: bdr:W8LS22914
  title: ཐེག་པ་ཆེན་པོ་བློ་སྦྱོང་བརྒྱ་རྩ།
  volumes:
    994b4ae28afa44319c6ff91d78d53a65:
      image_group_id: I8LS22916
      title: ''
      base_file: v001.txt
  author: ''
